# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bulletin_board.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bulletin_board.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ulletin_board.proto\x12\x08\x62ulletin\",\n\x0cShareRequest\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05share\x18\x02 \x01(\x0c\"\x1f\n\rShareResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1e\n\rCommitRequest\x12\r\n\x05index\x18\x01 \x01(\x05\" \n\x0e\x43ommitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"@\n\rVerifyRequest\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05share\x18\x02 \x01(\x0c\x12\x11\n\tserver_id\x18\x03 \x01(\t\" \n\x0eVerifyResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x93\x01\n\x0f\x44\x61tabaseService\x12>\n\x0bSubmitShare\x12\x16.bulletin.ShareRequest\x1a\x17.bulletin.ShareResponse\x12@\n\x0b\x43ommitShare\x12\x17.bulletin.CommitRequest\x1a\x18.bulletin.CommitResponse2P\n\x0c\x41uditService\x12@\n\x0bVerifyShare\x12\x17.bulletin.VerifyRequest\x1a\x18.bulletin.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bulletin_board_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHAREREQUEST']._serialized_start=34
  _globals['_SHAREREQUEST']._serialized_end=78
  _globals['_SHARERESPONSE']._serialized_start=80
  _globals['_SHARERESPONSE']._serialized_end=111
  _globals['_COMMITREQUEST']._serialized_start=113
  _globals['_COMMITREQUEST']._serialized_end=143
  _globals['_COMMITRESPONSE']._serialized_start=145
  _globals['_COMMITRESPONSE']._serialized_end=177
  _globals['_VERIFYREQUEST']._serialized_start=179
  _globals['_VERIFYREQUEST']._serialized_end=243
  _globals['_VERIFYRESPONSE']._serialized_start=245
  _globals['_VERIFYRESPONSE']._serialized_end=277
  _globals['_DATABASESERVICE']._serialized_start=280
  _globals['_DATABASESERVICE']._serialized_end=427
  _globals['_AUDITSERVICE']._serialized_start=429
  _globals['_AUDITSERVICE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
